# Supabase 프로젝트 설정 파일
# 이 파일은 로컬 개발 환경을 위한 설정입니다.
# 실제 프로덕션 환경에서는 Supabase 대시보드의 설정을 사용합니다.

[api]
# API 포트 (로컬 개발용)
port = 54321
# API 엔드포인트 스키마
schemas = ["public", "storage", "graphql_public"]
# 추가 검색 경로
extra_search_path = ["public"]
# 최대 행 수
max_rows = 1000

[db]
# 데이터베이스 포트 (로컬 개발용)
port = 54322
# Shadow 데이터베이스 (마이그레이션 검증용)
shadow_port = 54320
# 메이저 버전
major_version = 15

[studio]
# Supabase Studio 포트 (로컬 개발용)
port = 54323

[auth]
# 인증 활성화
enabled = true
# 사이트 URL
site_url = "http://localhost:3000"
# 추가 리다이렉트 URL
additional_redirect_urls = ["https://localhost:3000"]
# JWT 만료 시간 (초)
jwt_expiry = 3600
# 비밀번호 최소 길이
password_min_length = 6

[auth.email]
# 이메일 인증 활성화
enable_signup = true
# 이메일 확인 필수 여부
double_confirm_changes = true
# 확인 링크 만료 시간 (초)
max_frequency = 3600
